markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 5
paginate_path: page/:num

blog:
    name: 卢锦                                                # 博客名称
    description: 个人博客                                     # 博客描述
    title: 一个人的兵荒马乱                                   # 网页标题
    url: Jin-Lu.github.io                                     # 博客地址
    qiniu:                                                    # 七牛云地址
author:
    name: 卢锦                                                # 作者名称
    email: 1399350260@qq.com                                  # 邮箱地址
    weibo:                                                    # 微博地址
    github: https://github.com/Jin-Lu                         # GitHub地址
    logo: http://image.baidu.com/search/detail?ct=503316480&z=0&tn=baiduimagedetail&ipn=d&cl=2&cm=1&sc=0&lm=-1&ie=gbk&pn=0&rn=1&di=42737768590&ln=30&word=%C2%E8%CE%D2%D2%AA%BC%DE%B8%F8%CB%FB&os=1062382969,133645574&cs=3872644271,1737532062&objurl=http%3A%2F%2Fv1.qzone.cc%2Fpic%2F201507%2F15%2F22%2F22%2F55a66c996ee57110.jpg%21270x170.jpg&bdtype=0&simid=0,0&fr=ala&ori_query=%E5%A6%88%E6%88%91%E8%A6%81%E5%AB%81%E7%BB%99%E4%BB%96&ala=0&alatpl=sp&pos=1&timg=undefined&ctd=1453172477240^0_1423X773%0 # logo地址
    url: Jin-Lu.github.io                                     # 博客地址
    douban: 
        name:                                                 # 豆瓣地址名称
        key:                                                  # 豆瓣API Key

